"""create colaborators table

Revision ID: b55983f1c14a
Revises: e914ddaf3741
Create Date: 2026-08-24 10:34:42.986679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55983f1c14a'
down_revision: Union[str, Sequence[str], None] = 'e914ddaf3741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('matricula', sa.String(length=100), nullable=False),
    sa.Column('setor', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colaborators')
    # ### end Alembic commands ###
