"""create colaborators table

Revision ID: e914ddaf3741
Revises: 
Create Date: 2026-08-24 10:24:31.192854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e914ddaf3741'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colaborators',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('matricula', sa.String(length=100), nullable=False),
    sa.Column('setor', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colaborators')
    # ### end Alembic commands ###
